INSERT INTO movies (movieid, title, rating, image) VALUES (1, "Avengers: Endgame", 95, "avengers_endgame.jpg");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (1, 1, "1:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (2, 1, "2:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (3, 1, "3:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (4, 1, "4:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (5, 1, "5:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (6, 1, "6:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (7, 1, "7:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (8, 1, "8:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (9, 1, "9:00 PM");

INSERT INTO movies (movieid, title, rating, image) VALUES (2, "The Social Dilemma", 84, "social_dilemma.jpg");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (11, 2, "1:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (12, 2, "2:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (13, 2, "3:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (14, 2, "4:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (15, 2, "5:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (16, 2, "6:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (17, 2, "7:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (18, 2, "8:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (19, 2, "9:00 PM");

INSERT INTO movies (movieid, title, rating, image) VALUES (3, "Arrival", 79, "arrival.jpg");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (21, 3, "1:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (22, 3, "2:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (23, 3, "3:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (24, 3, "4:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (25, 3, "5:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (26, 3, "6:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (27, 3, "7:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (28, 3, "8:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (29, 3, "9:00 PM");

INSERT INTO movies (movieid, title, rating, image) VALUES (4, "Mission Impossible 45", 60, "mission_impossible.jpg");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (31, 4, "1:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (32, 4, "2:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (33, 4, "3:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (34, 4, "4:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (35, 4, "5:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (36, 4, "6:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (37, 4, "7:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (38, 4, "8:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (39, 4, "9:00 PM");

INSERT INTO movies (movieid, title, rating, image) VALUES (5, "The Dark Knight Rises", 95, "dark_knight_rises.jpg");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (41, 5, "1:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (42, 5, "2:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (43, 5, "3:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (44, 5, "4:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (45, 5, "5:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (46, 5, "6:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (47, 5, "7:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (48, 5, "8:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (49, 5, "9:00 PM");

INSERT INTO movies (movieid, title, rating, image) VALUES (6, "Knives Out!", 72, "knives_out.jpg");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (51, 6, "1:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (52, 6, "2:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (53, 6, "3:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (54, 6, "4:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (55, 6, "5:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (56, 6, "6:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (57, 6, "7:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (58, 6, "8:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (59, 6, "9:00 PM");

INSERT INTO movies (movieid, title, rating, image) VALUES (7, "Bee Movie", 60, "bee_movie.jpg");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (61, 7, "1:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (62, 7, "2:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (63, 7, "3:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (64, 7, "4:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (65, 7, "5:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (66, 7, "6:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (67, 7, "7:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (68, 7, "8:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (69, 7, "9:00 PM");

INSERT INTO movies (movieid, title, rating, image) VALUES (8, "Cars 3", 68, "cars_3.jpg");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (71, 8, "1:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (72, 8, "2:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (73, 8, "3:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (74, 8, "4:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (75, 8, "5:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (76, 8, "6:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (77, 8, "7:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (78, 8, "8:00 PM");
INSERT INTO showtimes (showtimeid, movieid, time) VALUES (79, 8, "9:00 PM");
